### ISSUE TITLE
Question with the config file for Jung dataset

### ISSUE THREAD

**Issue by baicenxiao** [CXH-Research/DocShadow-SD7K#15]
Dear author, thanks for sharing the great work! I have a question with the config file and the results. I tried to reproduce the result on Jung data reported in the table 5 of the paper, but I cannot achieve similar SSIM nor RMSE by using the default config file. The best SSIM and RMSE I got are 84.5 and 21.7, respectively, which are kinda far from the values reported in the paper.

Could you please share the configs for training on Jung dataset? Or if there are something else I need to adjust? Really appreciate your help on this issue.

For your reference, here are the parameters I use in the config file for training on the Jung's dataset:

```
VERBOSE: True

MODEL:
  SESSION: 'Jung'  # Define your current task here

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: '/users/bxiao/DocShadow-SD7K/data/Jung/train/' # path to training data
  VAL_DIR: '/users/bxiao/DocShadow-SD7K/data/Jung/test/'    # path to validation data
  SAVE_DIR: './checkpoints/'     # path to save models and images
  ORI: True

TESTING:
  WEIGHT: './checkpoints/best.pth'
  SAVE_IMAGES: True
```

Here is a screenshot of the result:
<img width="1373" alt="Screenshot 2024-05-01 at 11 34 47 AM" src="https://github.com/CXH-Research/DocShadow-SD7K/assets/32251365/3a3d3483-8431-44d3-9426-1dfd154c7e7f">

**Comment by zinuoli** [comment]
Hi, the result in table 5 was tested on 512 x 512 resolution. Here the `ORI: True` means you are testing on 2k resolution, where every method will not perform well.

I recommend you set `ORI: False` and save the best checkpoint, then test using `infer.py` to see if the result gets better. Otherwise, you can download our checkpoint release.

It has been late in my time zone, so I will get back to you tomorrow.

**Comment by baicenxiao** [comment]
Thank you so much for the prompt response! I have set `ORI: False`, retrained and saved the best model. It gives better result, but still not able to achieve that good PSNR and RMSE shown in the paper. Here are the new results by running `python infer.py` after retraining:
`PSNR: 21.928733825683594, SSIM: 0.8759468197822571, RMSE: 20.85166358947754`

In the paper, the values are: 
`PSNR: 24.36, SSIM: 0.88, RMSE: 16.04`

I used the data from this [link](https://www.kaggle.com/datasets/xuhangc/jungs-dataset) you shared (67 images for training and the 20 images for testing).

**Comment by zinuoli** [comment]
Hi, no worries, let me retrain here and get back to you.

**Comment by zinuoli** [comment]
Hi, I retrained on my laptop (3080ti instead of A6000) and got the similar result as paper. Performance may differ from different devices, but at least it's not that far. I am not sure if it's because the version difference of each package...
![image](https://github.com/CXH-Research/DocShadow-SD7K/assets/94612909/b445adbb-3b8f-4bd4-bcf1-0121304e1442)

**Comment by baicenxiao** [comment]
Thanks! Let me try on other server. Did you use the same parameters (except for the `batch_size`) like below to train on SD7K dataset? I may try on SD7K as well.

```
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: '/users/bxiao/DocShadow-SD7K/data/train/' # path to training data
  VAL_DIR: '/users/bxiao/DocShadow-SD7K/data/test/'    # path to validation data
  SAVE_DIR: './checkpoints/'     # path to save models and images
  ORI: False
```
